# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/police.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/police.proto\x12\x05proto\"[\n\x12GetPoliceUserEntry\x12\x11\n\tuser_long\x18\x01 \x01(\x01\x12\x10\n\x08user_lat\x18\x02 \x01(\x01\x12\x12\n\nzoom_index\x18\x03 \x01(\x03\x12\x0c\n\x04\x63ity\x18\x04 \x01(\t\"B\n\x0fPostPoliceEntry\x12\x10\n\x08pol_long\x18\x01 \x01(\x01\x12\x0f\n\x07pol_lat\x18\x02 \x01(\x01\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\"[\n\x12\x43onfirmPoliceEntry\x12\x10\n\x08pol_long\x18\x01 \x01(\x01\x12\x0f\n\x07pol_lat\x18\x02 \x01(\x01\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x14\n\x0c\x63onfirmation\x18\x04 \x01(\x08\",\n\x0ePoliceResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"g\n\nPoliceInfo\x12\x10\n\x08pol_long\x18\x01 \x01(\x01\x12\x0f\n\x07pol_lat\x18\x02 \x01(\x01\x12!\n\x19\x63onfirmation_notification\x18\x03 \x01(\x08\x12\x13\n\x0b\x63onfirmedBy\x18\x04 \x01(\x03\";\n\x11GetPoliceResponse\x12&\n\x0bpolice_info\x18\x01 \x03(\x0b\x32\x11.proto.PoliceInfo\"?\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x10\n\x08\x64\x61tabase\x18\x02 \x01(\t\x12\x0c\n\x04load\x18\x03 \x01(\x08\"\x0f\n\rHealthRequest\"B\n\x12\x46\x65tchPoliceRequest\x12,\n\tuser_info\x18\x01 \x01(\x0b\x32\x19.proto.GetPoliceUserEntry\"@\n\x11PostPoliceRequest\x12+\n\x0bpolice_info\x18\x01 \x01(\x0b\x32\x16.proto.PostPoliceEntry\"F\n\x14\x43onfirmPoliceRequest\x12.\n\x0bpolice_info\x18\x01 \x01(\x0b\x32\x19.proto.ConfirmPoliceEntry2\xa4\x02\n\x16PoliceReportingService\x12\x44\n\x0b\x46\x65tchPolice\x12\x19.proto.FetchPoliceRequest\x1a\x18.proto.GetPoliceResponse\"\x00\x12?\n\nPostPolice\x12\x18.proto.PostPoliceRequest\x1a\x15.proto.PoliceResponse\"\x00\x12\x45\n\rConfirmPolice\x12\x1b.proto.ConfirmPoliceRequest\x1a\x15.proto.PoliceResponse\"\x00\x12<\n\x0bHealthCheck\x12\x14.proto.HealthRequest\x1a\x15.proto.HealthResponse\"\x00\x42)Z\'github.com/senpainikolay/pad-sem7/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.police_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'github.com/senpainikolay/pad-sem7/proto'
  _globals['_GETPOLICEUSERENTRY']._serialized_start=29
  _globals['_GETPOLICEUSERENTRY']._serialized_end=120
  _globals['_POSTPOLICEENTRY']._serialized_start=122
  _globals['_POSTPOLICEENTRY']._serialized_end=188
  _globals['_CONFIRMPOLICEENTRY']._serialized_start=190
  _globals['_CONFIRMPOLICEENTRY']._serialized_end=281
  _globals['_POLICERESPONSE']._serialized_start=283
  _globals['_POLICERESPONSE']._serialized_end=327
  _globals['_POLICEINFO']._serialized_start=329
  _globals['_POLICEINFO']._serialized_end=432
  _globals['_GETPOLICERESPONSE']._serialized_start=434
  _globals['_GETPOLICERESPONSE']._serialized_end=493
  _globals['_HEALTHRESPONSE']._serialized_start=495
  _globals['_HEALTHRESPONSE']._serialized_end=558
  _globals['_HEALTHREQUEST']._serialized_start=560
  _globals['_HEALTHREQUEST']._serialized_end=575
  _globals['_FETCHPOLICEREQUEST']._serialized_start=577
  _globals['_FETCHPOLICEREQUEST']._serialized_end=643
  _globals['_POSTPOLICEREQUEST']._serialized_start=645
  _globals['_POSTPOLICEREQUEST']._serialized_end=709
  _globals['_CONFIRMPOLICEREQUEST']._serialized_start=711
  _globals['_CONFIRMPOLICEREQUEST']._serialized_end=781
  _globals['_POLICEREPORTINGSERVICE']._serialized_start=784
  _globals['_POLICEREPORTINGSERVICE']._serialized_end=1076
# @@protoc_insertion_point(module_scope)
