// protoc --go_out=internal/pb --go_opt=paths=source_relative --go-grpc_out=internal/pb --go-grpc_opt=paths=source_relative internal/proto/police.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: internal/proto/accident.proto

package accident_reporting_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PoliceReportingService_FetchAccidents_FullMethodName  = "/proto.PoliceReportingService/FetchAccidents"
	PoliceReportingService_PostAccident_FullMethodName    = "/proto.PoliceReportingService/PostAccident"
	PoliceReportingService_ConfirmAccident_FullMethodName = "/proto.PoliceReportingService/ConfirmAccident"
)

// PoliceReportingServiceClient is the client API for PoliceReportingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PoliceReportingServiceClient interface {
	FetchAccidents(ctx context.Context, in *FetchAccidentRequest, opts ...grpc.CallOption) (*GetAccidentResponse, error)
	PostAccident(ctx context.Context, in *PostAccidentRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	ConfirmAccident(ctx context.Context, in *ConfirmAccidentRequest, opts ...grpc.CallOption) (*GenericResponse, error)
}

type policeReportingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPoliceReportingServiceClient(cc grpc.ClientConnInterface) PoliceReportingServiceClient {
	return &policeReportingServiceClient{cc}
}

func (c *policeReportingServiceClient) FetchAccidents(ctx context.Context, in *FetchAccidentRequest, opts ...grpc.CallOption) (*GetAccidentResponse, error) {
	out := new(GetAccidentResponse)
	err := c.cc.Invoke(ctx, PoliceReportingService_FetchAccidents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policeReportingServiceClient) PostAccident(ctx context.Context, in *PostAccidentRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, PoliceReportingService_PostAccident_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policeReportingServiceClient) ConfirmAccident(ctx context.Context, in *ConfirmAccidentRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, PoliceReportingService_ConfirmAccident_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoliceReportingServiceServer is the server API for PoliceReportingService service.
// All implementations must embed UnimplementedPoliceReportingServiceServer
// for forward compatibility
type PoliceReportingServiceServer interface {
	FetchAccidents(context.Context, *FetchAccidentRequest) (*GetAccidentResponse, error)
	PostAccident(context.Context, *PostAccidentRequest) (*GenericResponse, error)
	ConfirmAccident(context.Context, *ConfirmAccidentRequest) (*GenericResponse, error)
	mustEmbedUnimplementedPoliceReportingServiceServer()
}

// UnimplementedPoliceReportingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPoliceReportingServiceServer struct {
}

func (UnimplementedPoliceReportingServiceServer) FetchAccidents(context.Context, *FetchAccidentRequest) (*GetAccidentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchAccidents not implemented")
}
func (UnimplementedPoliceReportingServiceServer) PostAccident(context.Context, *PostAccidentRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostAccident not implemented")
}
func (UnimplementedPoliceReportingServiceServer) ConfirmAccident(context.Context, *ConfirmAccidentRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmAccident not implemented")
}
func (UnimplementedPoliceReportingServiceServer) mustEmbedUnimplementedPoliceReportingServiceServer() {
}

// UnsafePoliceReportingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoliceReportingServiceServer will
// result in compilation errors.
type UnsafePoliceReportingServiceServer interface {
	mustEmbedUnimplementedPoliceReportingServiceServer()
}

func RegisterPoliceReportingServiceServer(s grpc.ServiceRegistrar, srv PoliceReportingServiceServer) {
	s.RegisterService(&PoliceReportingService_ServiceDesc, srv)
}

func _PoliceReportingService_FetchAccidents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchAccidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoliceReportingServiceServer).FetchAccidents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoliceReportingService_FetchAccidents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoliceReportingServiceServer).FetchAccidents(ctx, req.(*FetchAccidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoliceReportingService_PostAccident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostAccidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoliceReportingServiceServer).PostAccident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoliceReportingService_PostAccident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoliceReportingServiceServer).PostAccident(ctx, req.(*PostAccidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoliceReportingService_ConfirmAccident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmAccidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoliceReportingServiceServer).ConfirmAccident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoliceReportingService_ConfirmAccident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoliceReportingServiceServer).ConfirmAccident(ctx, req.(*ConfirmAccidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PoliceReportingService_ServiceDesc is the grpc.ServiceDesc for PoliceReportingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoliceReportingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PoliceReportingService",
	HandlerType: (*PoliceReportingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchAccidents",
			Handler:    _PoliceReportingService_FetchAccidents_Handler,
		},
		{
			MethodName: "PostAccident",
			Handler:    _PoliceReportingService_PostAccident_Handler,
		},
		{
			MethodName: "ConfirmAccident",
			Handler:    _PoliceReportingService_ConfirmAccident_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/accident.proto",
}
