// protoc --go_out=internal/pb --go_opt=paths=source_relative --go-grpc_out=internal/pb --go-grpc_opt=paths=source_relative internal/proto/police.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: internal/proto/police.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PoliceReportingService_FetchPolice_FullMethodName   = "/proto.PoliceReportingService/FetchPolice"
	PoliceReportingService_PostPolice_FullMethodName    = "/proto.PoliceReportingService/PostPolice"
	PoliceReportingService_ConfirmPolice_FullMethodName = "/proto.PoliceReportingService/ConfirmPolice"
	PoliceReportingService_HealthCheck_FullMethodName   = "/proto.PoliceReportingService/HealthCheck"
)

// PoliceReportingServiceClient is the client API for PoliceReportingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PoliceReportingServiceClient interface {
	FetchPolice(ctx context.Context, in *FetchPoliceRequest, opts ...grpc.CallOption) (*GetPoliceResponse, error)
	PostPolice(ctx context.Context, in *PostPoliceRequest, opts ...grpc.CallOption) (*PoliceResponse, error)
	ConfirmPolice(ctx context.Context, in *ConfirmPoliceRequest, opts ...grpc.CallOption) (*PoliceResponse, error)
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type policeReportingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPoliceReportingServiceClient(cc grpc.ClientConnInterface) PoliceReportingServiceClient {
	return &policeReportingServiceClient{cc}
}

func (c *policeReportingServiceClient) FetchPolice(ctx context.Context, in *FetchPoliceRequest, opts ...grpc.CallOption) (*GetPoliceResponse, error) {
	out := new(GetPoliceResponse)
	err := c.cc.Invoke(ctx, PoliceReportingService_FetchPolice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policeReportingServiceClient) PostPolice(ctx context.Context, in *PostPoliceRequest, opts ...grpc.CallOption) (*PoliceResponse, error) {
	out := new(PoliceResponse)
	err := c.cc.Invoke(ctx, PoliceReportingService_PostPolice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policeReportingServiceClient) ConfirmPolice(ctx context.Context, in *ConfirmPoliceRequest, opts ...grpc.CallOption) (*PoliceResponse, error) {
	out := new(PoliceResponse)
	err := c.cc.Invoke(ctx, PoliceReportingService_ConfirmPolice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policeReportingServiceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PoliceReportingService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoliceReportingServiceServer is the server API for PoliceReportingService service.
// All implementations must embed UnimplementedPoliceReportingServiceServer
// for forward compatibility
type PoliceReportingServiceServer interface {
	FetchPolice(context.Context, *FetchPoliceRequest) (*GetPoliceResponse, error)
	PostPolice(context.Context, *PostPoliceRequest) (*PoliceResponse, error)
	ConfirmPolice(context.Context, *ConfirmPoliceRequest) (*PoliceResponse, error)
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedPoliceReportingServiceServer()
}

// UnimplementedPoliceReportingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPoliceReportingServiceServer struct {
}

func (UnimplementedPoliceReportingServiceServer) FetchPolice(context.Context, *FetchPoliceRequest) (*GetPoliceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchPolice not implemented")
}
func (UnimplementedPoliceReportingServiceServer) PostPolice(context.Context, *PostPoliceRequest) (*PoliceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostPolice not implemented")
}
func (UnimplementedPoliceReportingServiceServer) ConfirmPolice(context.Context, *ConfirmPoliceRequest) (*PoliceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmPolice not implemented")
}
func (UnimplementedPoliceReportingServiceServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPoliceReportingServiceServer) mustEmbedUnimplementedPoliceReportingServiceServer() {
}

// UnsafePoliceReportingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoliceReportingServiceServer will
// result in compilation errors.
type UnsafePoliceReportingServiceServer interface {
	mustEmbedUnimplementedPoliceReportingServiceServer()
}

func RegisterPoliceReportingServiceServer(s grpc.ServiceRegistrar, srv PoliceReportingServiceServer) {
	s.RegisterService(&PoliceReportingService_ServiceDesc, srv)
}

func _PoliceReportingService_FetchPolice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPoliceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoliceReportingServiceServer).FetchPolice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoliceReportingService_FetchPolice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoliceReportingServiceServer).FetchPolice(ctx, req.(*FetchPoliceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoliceReportingService_PostPolice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostPoliceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoliceReportingServiceServer).PostPolice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoliceReportingService_PostPolice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoliceReportingServiceServer).PostPolice(ctx, req.(*PostPoliceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoliceReportingService_ConfirmPolice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPoliceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoliceReportingServiceServer).ConfirmPolice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoliceReportingService_ConfirmPolice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoliceReportingServiceServer).ConfirmPolice(ctx, req.(*ConfirmPoliceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoliceReportingService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoliceReportingServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoliceReportingService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoliceReportingServiceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PoliceReportingService_ServiceDesc is the grpc.ServiceDesc for PoliceReportingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoliceReportingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PoliceReportingService",
	HandlerType: (*PoliceReportingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchPolice",
			Handler:    _PoliceReportingService_FetchPolice_Handler,
		},
		{
			MethodName: "PostPolice",
			Handler:    _PoliceReportingService_PostPolice_Handler,
		},
		{
			MethodName: "ConfirmPolice",
			Handler:    _PoliceReportingService_ConfirmPolice_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PoliceReportingService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/police.proto",
}
